### ISSUE TITLE
模板创建的项目0.13.0.1版本升级到0.14版本，页面加载不出来报错了。

### ISSUE THREAD

**Issue by ZetRe** [ant-design-blazor/blazor-pro-components#73]
/__w/1/s/src/mono/mono/eglib/gpath.c:115 <disabled>
/__w/1/s/src/mono/mono/eglib/gpath.c:115 <disabled>
info: AntDesign.ProLayout.BasicLayout[0]
      BasicLayout initialized.
info: AntDesign.ProLayout.BaseMenu[0]
      BaseMenu initialized.
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: No element is currently associated with component 11
      Error: No element is currently associated with component 11
          at ae.updateComponent (https://localhost:44358/_framework/blazor.webassembly.js:1:19821)
          at https://localhost:44358/_framework/blazor.webassembly.js:1:56876
          at St.Te._internal.renderBatch (https://localhost:44358/_framework/blazor.webassembly.js:1:57248)
          at Object.Rt [as invokeJSFromDotNet] (https://localhost:44358/_framework/blazor.webassembly.js:1:59934)
          at _mono_wasm_invoke_js_blazor (https://localhost:44358/_framework/dotnet.6.0.16.olpkzvz1qs.js:1:195300)
          at wasm://wasm/00971dfe:wasm-function[3308]:0xc6137
          at wasm://wasm/00971dfe:wasm-function[167]:0xd602
          at wasm://wasm/00971dfe:wasm-function[166]:0xbd73
          at wasm://wasm/00971dfe:wasm-function[2815]:0xabef4
          at wasm://wasm/00971dfe:wasm-function[1619]:0x6fcb4
Microsoft.JSInterop.JSException: No element is currently associated with component 11
Error: No element is currently associated with component 11
    at ae.updateComponent (https://localhost:44358/_framework/blazor.webassembly.js:1:19821)
    at https://localhost:44358/_framework/blazor.webassembly.js:1:56876
    at St.Te._internal.renderBatch (https://localhost:44358/_framework/blazor.webassembly.js:1:57248)
    at Object.Rt [as invokeJSFromDotNet] (https://localhost:44358/_framework/blazor.webassembly.js:1:59934)
    at _mono_wasm_invoke_js_blazor (https://localhost:44358/_framework/dotnet.6.0.16.olpkzvz1qs.js:1:195300)
    at wasm://wasm/00971dfe:wasm-function[3308]:0xc6137
    at wasm://wasm/00971dfe:wasm-function[167]:0xd602
    at wasm://wasm/00971dfe:wasm-function[166]:0xbd73
    at wasm://wasm/00971dfe:wasm-function[2815]:0xabef4
    at wasm://wasm/00971dfe:wasm-function[1619]:0x6fcb4
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by ZetRe** [comment]
不用了， 找到问题了， 14版本中ReuseTabsRouteView这个不用了，换成下面就好了
 <CascadingValue Value="routeData">
            <RouteView RouteData="@routeData" DefaultLayout="@typeof(BasicLayout)" />
        </CascadingValue>
